name: ci/cd common lib

on:
  push:
    branches:
      - "develop"
      - "staging"
      - "dss-prd"

env:
  DOCKER_REPO: heligate2023/vtp-crm-common

jobs:
  setup-env-vars:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-outputs.outputs.image_tag }}

    steps:
      - name: Set Environment Variable develop
        if: github.ref == 'refs/heads/develop'
        run: |
          echo "IMAGE_TAG=develop" >> $GITHUB_ENV

      - name: Set Environment Variable staging
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "IMAGE_TAG=staging" >> $GITHUB_ENV

      - name: Set Environment Variable dss-prd
        if: github.ref == 'refs/heads/dss-prd'
        run: |
          echo "IMAGE_TAG=dss-prd" >> $GITHUB_ENV

      - name: Set outputs
        id: set-outputs
        run: |
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

  build-and-push-dockerhub:
    needs: setup-env-vars
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./dev.Dockerfile
          push: true
          tags: ${{ env.DOCKER_REPO }}:${{ needs.setup-env-vars.outputs.image_tag }}
