name: Publish package to GitHub Packages
on:
  release:
    types: [created]
  push:
    branches:
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish package
        run: mvn clean deploy --batch-mode
        env:
          GITHUB_ACTOR: ${{ vars.GH_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
